# Generated by Django 4.2.14 on 2026-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastSafe', '0005_delete_donation_subscription_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/', verbose_name='Fichier vidéo local'),
        ),
    ]
