# Generated by Django 4.2.14 on 2026-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastSafe', '0010_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('don', 'Don'), ('ceremonie', 'Cérémonie'), ('conference', 'Conférence'), ('priere', 'Prière'), ('culte', 'Culte'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type')),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('is_online', models.BooleanField(default=False, verbose_name='En ligne')),
                ('online_url', models.URLField(blank=True, verbose_name='Lien en ligne')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='Image')),
                ('registration_url', models.URLField(blank=True, verbose_name="Lien d'inscription")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['event_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['for_type', 'name'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterField(
            model_name='multistreamconfig',
            name='custom_rtmp',
            field=models.CharField(blank=True, help_text='Autre plateforme RTMP', max_length=600),
        ),
        migrations.AlterField(
            model_name='multistreamconfig',
            name='instagram_rtmp',
            field=models.CharField(blank=True, help_text='rtmp://live-api-s.facebook.com:80/rtmp/VOTRE_CLÉ', max_length=600),
        ),
        migrations.AlterField(
            model_name='multistreamconfig',
            name='tiktok_rtmp',
            field=models.CharField(blank=True, help_text='rtmp://live.tiktok.com/live/VOTRE_CLÉ', max_length=600),
        ),
        migrations.AlterField(
            model_name='multistreamconfig',
            name='video_quality',
            field=models.CharField(choices=[('360p', '360p — 800 kbps (connexion lente)'), ('480p', '480p — 1500 kbps'), ('720p', '720p — 2500 kbps (recommandé)'), ('1080p', '1080p — 4500 kbps (fibre)')], default='720p', max_length=10),
        ),
        migrations.AlterField(
            model_name='multistreamconfig',
            name='youtube_rtmp',
            field=models.CharField(blank=True, help_text='rtmp://a.rtmp.youtube.com/live2/VOTRE_CLÉ', max_length=600),
        ),
    ]
